In [1]:
import numpy as np

In [8]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr.flatten("F")

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [15]:
np.linspace(1,3,10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])