In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(3,12).reshape(3,3)
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [3]:
arr1 + arr2

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [4]:
arr1 * arr2

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [5]:
arr1 / arr2 

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ],
       [0.77777778, 0.8       , 0.81818182]])

In [7]:
np.dot(arr1,arr2)# this is dot product

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [8]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr1[0,0] = 5
arr1

array([[5, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr1

array([[5, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate([arr1,arr2])  # merge 2 array

array([[ 5,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.split(arr1,3) 

[array([[5, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [22]:
np.split(arr1,3,axis=1)  # by default axis = 0 means row, if we do axis=1 it deos coloumn wise

[array([[5],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]