In [1]:
import numpy as np

In [3]:
arr = np.arange(1,43).reshape((6,7))
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [4]:
arr[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [5]:
arr[1:5,0:6]

array([[ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27],
       [29, 30, 31, 32, 33, 34]])

In [7]:
arr[:,-1]

array([ 7, 14, 21, 28, 35, 42])

In [8]:
arr[-1]

array([36, 37, 38, 39, 40, 41, 42])

In [9]:
arr[:,4:6]

array([[ 5,  6],
       [12, 13],
       [19, 20],
       [26, 27],
       [33, 34],
       [40, 41]])

In [14]:
arr[0,0] # indicates the element in the 0th row and 0th coloumn

np.int64(1)

In [15]:
arr[:,:-1]

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27],
       [29, 30, 31, 32, 33, 34],
       [36, 37, 38, 39, 40, 41]])