##### Perform the following operations on an array of mobile phones prices 6999, 7500,
##### 11999, 27899, 14999, 9999.
##### a. Create a 1d-array of mobile phones prices
##### b. Convert this array to float type
##### c. Append a new mobile having price of 13999 Rs. to this array
##### d. Reverse this array of mobile phones prices
##### e. Apply GST of 18% on mobile phones prices and update this array.
##### f. Sort the array in descending order of price
##### g. What is the average mobile phone price
##### h. What is the difference b/w maximum and minimum price

In [1]:
import numpy as np

In [2]:
arr = np.array([6999, 7500,11999, 27899, 14999, 9999])
arr

array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [3]:
type(arr)

numpy.ndarray

In [5]:
arr = arr.astype(float)

In [6]:
arr

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

In [7]:
arr = np.append(arr, 13999.0)
arr

array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

In [9]:
arr = arr[::-1]
arr

array([13999.,  9999., 14999., 27899., 11999.,  7500.,  6999.])

In [10]:
arr = arr*1.18
arr

array([16518.82, 11798.82, 17698.82, 32920.82, 14158.82,  8850.  ,
        8258.82])

In [12]:
arr = np.sort(arr)[::-1]
arr

array([32920.82, 17698.82, 16518.82, 14158.82, 11798.82,  8850.  ,
        8258.82])

In [13]:
arr_avg = np.mean(arr)

In [14]:
arr_avg

np.float64(15743.560000000001)

In [16]:
price_diff = np.max(arr) - np.min(arr)
price_diff

np.float64(24662.0)